version: '3.4'

services:

  MSSQLServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    env_file:
      - .env
    volumes: 
      - ./../stackoverflow-small:/var/opt/mssql/data

  redisServer:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass mqsdfhmjkjKJFapaekrJqq
    volumes: 
      - ./redis-cache:/data


