version: '3.4'

services:

   sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    env_file:
      - .env
    volumes: 
      - ./../stackoverflow-large:/var/opt/mssql/data

