
   
version: "3.4"

services:
  mssqldb:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    env_file:
      - .env
    volumes:
      - ./../stackoverflowdb:/var/opt/mssql/data

  # Only needed on redis branch
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass mqsdfhmjkjKJFapaekrJqq
    volumes:
      - ./redis-cache:/data

  api-server-express:
    # restart always because db needs some time to start connectons
    restart: always
    build:
      context: ./typegql-server
      dockerfile: Dockerfile
    env_file:
      - ./typegql-server/docker.ormconfig.env
      - ./typegql-server/.env
    ports:
      - 4000:4000
    depends_on:
      - redis
      - mssqldb

  client-server-next:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000